### ISSUE TITLE
블록의 생성과 저장기능에 대한 예외처리 강화

### ISSUE THREAD

**Issue by MichaelKim20** [bosagora/rollup-server#12]
블록생성과 저장하는 절차는 다음과 같다.

1. 트랜잭션 풀에서 트랜잭션 추출 -> 2. 블록생성 -> 3. IPFS블록을 저장 -> 4. Contract에 블록해드 및 CID저장

규칙1) 1번에서 추출된 트랜잭션을 풀에서 제거하지 않고 3번까지 완료된 블럭에 대해서 트랜잭션을 제거한다.
규칙2) 3번에서 실패하면 생성된 블록을 제거하고, 성공하면 데이타베이스에 블록의 내용과 CID 기록하고, 다음단계로 진행한다.
규칙3) 4번에서 실패하면 10초뒤에 반복할 수 있도록 데이타베이스에 기록한다.
규칙4) 노드는3번과 4번 지속적으로 문제발생시 관리자가 조치할 있도록 오류사항을 기록하고 metrics를 통해 제공한다.

**Comment by TrustHenry** [comment]
규칙1) 1번에서 추출된 트랜잭션을 풀에서 제거하지 않고 3번까지 완료된 블럭에 대해서 **트랜잭션 풀 에서** 트랜잭션을 제거한다.
이렇게 추가하면 더욱 명확해 보입니다. ^^

**Comment by TrustHenry** [comment]
규칙2) 에서 3번에서 실패한경우(IPFS블록을 저장) 2번에서 생성된 블록을 제거 해야 할까요?

**Comment by MichaelKim20** [comment]
> 규칙2) 에서 3번에서 실패한경우(IPFS블록을 저장) 2번에서 생성된 블록을 제거 해야 할까요?

트랜잭션 풀에 트랜잭션들이 남아 있기 때문에 제거할 계획입니다
