### ISSUE TITLE
블록의 해드 정보를 저장하는 스마트컨트랙트를 구현

### ISSUE THREAD

**Issue by MichaelKim20** [bosagora/rollup-server#7]
스마트컨트랙트에 저장될 데이타는 다음같다.
다수의 블록헤드가 스마트컨트랙트에 저장되면 하나의 블록에 대해서는
```
이전 블록의 해시   현재 블록의 해시
머클루트
타임스탬프  
블록높이
IPFS에 저장된 블록파일의 CID
```
블록의 해시로 정보를 검색할 수 있고, 블록의 높이로도 검색할 있도록 한다.

**Comment by TrustHenry** [comment]
스마트컨트랙트 에 저장 할 수 있는 권한은 컨트랙트 소유자만 할 수 있습니까?

**Comment by MichaelKim20** [comment]
> 스마트컨트랙트 에 저장 할 수 있는 권한은 컨트랙트 소유자만 할 수 있습니까?

네 소유자만이 할 수 있습니다. 
그렇지 않으면 스마트컨트랙트에 소유자의 키를 등록하고, 스마트컨트랙트에 데이타를 입력할 때 해당키로 서명정보를 전달한후, 스마트컨트랙트에서 검증이된 데이타만 저장하면 됩니다.

**Comment by TrustHenry** [comment]
#31
